#!/bin/bash
#
#### Homebrew stuff ###
__log "00-homebrew start"
HOMEBREW="$(which brew 2>/dev/null)"
if [ -n "$HOMEBREW" ] ; then
    # Make sure brew path comes first so its executables
    # are found before defaults.  Specifically helpful for
    # php and other things already provided by OSX.
    export PATH
    PATH="$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH"

    ### bash-completion ###
    __log "00-homebrew bash-completion"
    if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
        # shellcheck disable=SC1090
        . "$(brew --prefix)/etc/bash_completion"
    fi
fi
