#!/bin/bash
#
#### python ###
export PIP_RESPECT_VIRTUALENV=true
# export PIP_REQUIRE_VIRTUALENV=true
export PYTHONDONTWRITEBYTECODE=true
export VIRTUAL_ENV_DISABLE_PROMPT=1

# `pip install --user` installs to ~/.local
if [[ -d ~/.local/bin ]]; then
    export PATH=$PATH:~/.local/bin
fi

if [ -n "$(which pyenv 2>/dev/null)" ] ; then
    __log "pyenv init"
    eval "$(pyenv init -)"
fi
