#!/usr/bin/env bash

# Functions for working inside of iTerm2.

iterm2_set_profile() {
    local profile="$1"
    printf "\x1B]1337;SetProfile=${profile}\x07"
    ITERM_PROFILE="$profile"
}


bg_light() {
    iterm2_set_profile "Light"
    clear
}

bg_dark() {
    iterm2_set_profile "Dark"
    clear
}
