---
#
# Bootstrap:
# install ansible via brew

- hosts: localhost
  connection: local

  tasks:
    - name: bash config
      file:
        state: link
        src: "{{ playbook_dir }}/{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
      with_items:
        - src: bash/bash_profile
          dest: .bash_profile
        - src: bash/bashrc
          dest: .bashrc
        - src: bash/bash_prompt
          dest: .bash_prompt

    - name: tmux config
      file: 
        state: link
        src: "{{ playbook_dir }}/{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
      with_items:
        - src: tmux/tmux.conf
          dest: .tmux.conf

    - name: psql config
      file: 
        state: link
        src: "{{ playbook_dir }}/{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
      with_items:
        - src: psqlrc
          dest: .psqlrc

    - name: git config
      file:
        state: link
        src: "{{ playbook_dir }}/{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
      with_items:
        - src: git/gitconfig
          dest: .gitconfig
        - src: git/gitignore
          dest: .gitignore
        - src: git/git_template
          dest: .git_template

    - name: vim directories
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/{{ item }}"
      with_items:
        - .vim
        - .vim/autoload

    - name: vim config
      file:
        state: link
        src: "{{ playbook_dir }}/{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
      with_items:
        - src: vim/vimrc
          dest: .vimrc
      notify:
        - install vim plugins

    - name: download vim-plug
      get_url:
        url: "https://github.com/junegunn/vim-plug/releases/download/0.9.1/plug.vim"
        dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
        checksum: "sha1:58f88309277ff657151397df930d7f4dd6f50d19"
      notify:
        - install vim plugins

  handlers:
    - name: install vim plugins
      shell: vim "+PlugInstall" "+qall"
