# -*- mode: shell-script -*-

#__DOTFILES_DEBUG=1

__log() {
    if [ ! -z "${__DOTFILES_DEBUG}" ]; then
        echo "[DEBUG] ${1} (${SECONDS} seconds)"
    fi
}

__log "Entered .bashrc"

### Basic config ###
export CLICOLOR=1
export EDITOR=$(which vim 2>/dev/null)

### Include modules from .bashrc.d
if [ -d ~/.bashrc.d ]; then
    __log "Loading modules from .bashrc.d"
    for f in ~/.bashrc.d/*; do
        __log "Loading $f"
        source $f;
    done
fi

# use .localrc for settings specific to one system
if [ -f ~/.localrc ]; then
  __log ".localrc"
  source ~/.localrc
fi

### Anything below this only applies to an interactive session.  ###
[[ $- = *i* ]] || return

# Handle resizes gracefully.
shopt -s checkwinsize
